ALTER TYPE "BlockType" ADD VALUE IF NOT EXISTS 'IMAGE';
ALTER TYPE "BlockType" ADD VALUE IF NOT EXISTS 'SOCIAL';
ALTER TYPE "BlockType" ADD VALUE IF NOT EXISTS 'DIVIDER';
ALTER TYPE "BlockType" ADD VALUE IF NOT EXISTS 'YOUTUBE';
ALTER TYPE "BlockType" ADD VALUE IF NOT EXISTS 'SPOTIFY';
ALTER TYPE "BlockType" ADD VALUE IF NOT EXISTS 'EMAIL';
ALTER TYPE "BlockType" ADD VALUE IF NOT EXISTS 'PHONE';
ALTER TYPE "BlockType" ADD VALUE IF NOT EXISTS 'LOCATION';
