"use client";

import Link from "next/link";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import type { ContactStatus } from "@kachko/types";
import { addContactNote, addContactTag, getContact, listContacts, removeContactTag, updateContact } from "./api";

const statuses: ContactStatus[] = ["NEW", "CONTACTED", "QUALIFIED", "WON", "LOST"];

export function AudiencePanel() {
  const [search, setSearch] = useState(""); const [status, setStatus] = useState("");
  const params = new URLSearchParams(); if (search) params.set("search", search); if (status) params.set("status", status);
  const query = useQuery({ queryKey: ["audience", search, status], queryFn: () => listContacts(params.toString()) });
  return <section><div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-[26px] font-extrabold tracking-[-1px]">Audience</h1><p className="mt-1 text-sm text-[var(--k-muted)]">Contacts captured through your forms and subscriptions.</p></div><a href="/api/v1/audience/export" className="k-btn-line" download>Export CSV</a></div><div className="k-panel p-5"><div className="mb-4 grid gap-3 sm:grid-cols-[1fr_auto]"><input className="k-input" type="search" placeholder="Search name, email or phone" value={search} onChange={event => setSearch(event.target.value)} /><select className="k-input !w-auto" value={status} onChange={event => setStatus(event.target.value)}><option value="">All statuses</option>{statuses.map(value => <option key={value}>{value}</option>)}</select></div>{query.isLoading ? <p className="py-8 text-center text-sm text-[var(--k-muted)]">Loading contacts…</p> : query.isError ? <p role="alert" className="py-8 text-center text-sm text-red-700">Could not load contacts.</p> : !query.data?.items.length ? <p className="py-8 text-center text-sm text-[var(--k-muted)]">No contacts match this view.</p> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs uppercase text-[var(--k-muted)]"><tr><th className="pb-3">Contact</th><th className="pb-3">Source</th><th className="pb-3">Status</th><th className="pb-3">Created</th></tr></thead><tbody>{query.data.items.map(contact => { const label = contact.name ?? contact.email ?? contact.phone ?? "Contact"; const secondary = contact.email !== label ? contact.email : contact.phone !== label ? contact.phone : null; return <tr key={contact.id} className="border-t border-[#eceee9]"><td className="py-3"><Link href={`/dashboard/audience/${contact.id}`} className="font-extrabold hover:underline">{label}</Link>{secondary ? <span className="block text-xs text-[var(--k-muted)]">{secondary}</span> : null}</td><td>{contact.source ?? "Form"}</td><td><span className="rounded-full bg-[#eff8d4] px-2 py-1 text-xs font-bold">{contact.status}</span></td><td>{new Date(contact.createdAt).toLocaleDateString()}</td></tr>; })}</tbody></table></div>}<p className="mt-4 text-xs text-[var(--k-muted)]">{query.data?.total ?? 0} contacts</p></div></section>;
}

export function ContactDetailPanel({ id }: { id: string }) {
  const qc = useQueryClient(); const key = ["contact", id]; const query = useQuery({ queryKey: key, queryFn: () => getContact(id) });
  const [note, setNote] = useState(""); const [tag, setTag] = useState("");
  const mutation = useMutation({ mutationFn: (job: () => Promise<unknown>) => job(), onSuccess: () => { setNote(""); setTag(""); void qc.invalidateQueries({ queryKey: key }); void qc.invalidateQueries({ queryKey: ["audience"] }); } });
  if (query.isLoading) return <div className="k-panel p-10 text-center">Loading contact…</div>; if (!query.data) return <div role="alert" className="k-panel p-10 text-red-700">Contact not found.</div>;
  const contact = query.data;
  return <section><Link href="/dashboard/audience" className="text-sm font-bold text-[var(--k-muted)]">← Audience</Link><div className="mt-4 flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-[26px] font-extrabold">{contact.name ?? contact.email ?? contact.phone}</h1><p className="text-sm text-[var(--k-muted)]">{contact.email} {contact.phone}</p></div><select className="k-input !w-auto" value={contact.status} onChange={event => mutation.mutate(() => updateContact(id, { status: event.target.value as ContactStatus }))}>{statuses.map(value => <option key={value}>{value}</option>)}</select></div><div className="mt-5 grid gap-5 lg:grid-cols-2"><div className="k-panel p-5"><p className="k-label">Tags</p><div className="flex flex-wrap gap-2">{contact.tags.map(item => <button key={item.id} className="rounded-full bg-[#eff8d4] px-3 py-1 text-xs font-bold" title="Remove tag" onClick={() => mutation.mutate(() => removeContactTag(id, item.id))}>{item.name} ×</button>)}</div><div className="mt-3 flex gap-2"><input className="k-input" value={tag} onChange={event => setTag(event.target.value)} placeholder="Add tag" /><button className="k-btn-ink" disabled={!tag.trim()} onClick={() => mutation.mutate(() => addContactTag(id, tag.trim()))}>Add</button></div><p className="k-label mt-6">Notes</p><div className="flex gap-2"><textarea className="k-input min-h-20" value={note} onChange={event => setNote(event.target.value)} placeholder="Add a private note" /><button className="k-btn-ink self-end" disabled={!note.trim()} onClick={() => mutation.mutate(() => addContactNote(id, note.trim()))}>Save</button></div><ul className="mt-3 grid gap-2">{contact.notes.map(item => <li key={item.id} className="rounded-xl bg-[#f7f8f3] p-3 text-sm">{item.note}<span className="mt-1 block text-[10px] text-[var(--k-muted)]">{new Date(item.createdAt).toLocaleString()}</span></li>)}</ul></div><div className="k-panel p-5"><p className="k-label">Submissions</p><div className="grid gap-3">{contact.submissions.map(item => <article key={item.id} className="rounded-xl border border-[#eceee9] p-3"><p className="text-sm font-extrabold">{item.formName}</p><dl className="mt-2 grid gap-1 text-xs">{Object.entries(item.payload).map(([key, value]) => <div key={key} className="grid grid-cols-[120px_1fr] gap-2"><dt className="text-[var(--k-muted)]">{key}</dt><dd className="break-words">{String(value)}</dd></div>)}</dl><p className="mt-2 text-[10px] text-[var(--k-muted)]">{new Date(item.createdAt).toLocaleString()}</p></article>)}</div></div></div>{mutation.error ? <p role="alert" className="mt-3 text-sm text-red-700">{mutation.error.message}</p> : null}</section>;
}
