CREATE TABLE "Theme" (
 "id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "slug" TEXT NOT NULL,
 "isSystem" BOOLEAN NOT NULL DEFAULT true,
 "background" JSONB NOT NULL, "typography" JSONB NOT NULL, "buttons" JSONB NOT NULL, "cards" JSONB NOT NULL,
 "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL
);
CREATE UNIQUE INDEX "Theme_slug_key" ON "Theme"("slug");
CREATE TABLE "PageTemplate" (
 "key" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "description" TEXT NOT NULL,
 "themeKey" TEXT NOT NULL, "blocks" JSONB NOT NULL,
 CONSTRAINT "PageTemplate_themeKey_fkey" FOREIGN KEY ("themeKey") REFERENCES "Theme"("slug") ON DELETE RESTRICT ON UPDATE CASCADE
);
INSERT INTO "Theme" ("id","name","slug","background","typography","buttons","cards","updatedAt") VALUES ('03d0e2d7-55ea-5266-8024-478ee80e1932','Minimal','minimal','{"type": "solid", "color": "#FFFFFF"}'::jsonb,'{"fontFamily": "system", "titleSize": 32, "color": "#111827"}'::jsonb,'{"variant": "filled", "radius": 12, "background": "#111827", "color": "#FFFFFF", "shadow": false}'::jsonb,'{"radius": 12, "background": "#FFFFFF", "blur": 0}'::jsonb,CURRENT_TIMESTAMP);
INSERT INTO "Theme" ("id","name","slug","background","typography","buttons","cards","updatedAt") VALUES ('bfdabb87-1461-511e-99b9-cccb69deb0cb','Dark','dark','{"type": "solid", "color": "#111827"}'::jsonb,'{"fontFamily": "system", "titleSize": 32, "color": "#F9FAFB"}'::jsonb,'{"variant": "filled", "radius": 12, "background": "#F9FAFB", "color": "#111827", "shadow": false}'::jsonb,'{"radius": 12, "background": "#111827", "blur": 0}'::jsonb,CURRENT_TIMESTAMP);
INSERT INTO "Theme" ("id","name","slug","background","typography","buttons","cards","updatedAt") VALUES ('e0572b3c-8958-5f76-8924-74eed8b4386c','Gradient','gradient','{"type": "gradient", "from": "#312E81", "to": "#831843", "angle": 135}'::jsonb,'{"fontFamily": "sans", "titleSize": 32, "color": "#FFFFFF"}'::jsonb,'{"variant": "filled", "radius": 20, "background": "#FFFFFF", "color": "#312E81", "shadow": false}'::jsonb,'{"radius": 20, "background": "#312E81", "blur": 0}'::jsonb,CURRENT_TIMESTAMP);
INSERT INTO "Theme" ("id","name","slug","background","typography","buttons","cards","updatedAt") VALUES ('675175a1-c647-5d0b-899b-5909b2e9cc3e','Professional','professional','{"type": "solid", "color": "#F1F5F9"}'::jsonb,'{"fontFamily": "sans", "titleSize": 32, "color": "#0F172A"}'::jsonb,'{"variant": "filled", "radius": 8, "background": "#1D4ED8", "color": "#FFFFFF", "shadow": false}'::jsonb,'{"radius": 8, "background": "#F1F5F9", "blur": 0}'::jsonb,CURRENT_TIMESTAMP);
INSERT INTO "Theme" ("id","name","slug","background","typography","buttons","cards","updatedAt") VALUES ('6e917071-0b6d-5cc8-9f9c-16ddad66f057','Elegant','elegant','{"type": "solid", "color": "#FFF7ED"}'::jsonb,'{"fontFamily": "serif", "titleSize": 32, "color": "#431407"}'::jsonb,'{"variant": "filled", "radius": 8, "background": "#7C2D12", "color": "#FFFFFF", "shadow": false}'::jsonb,'{"radius": 8, "background": "#FFF7ED", "blur": 0}'::jsonb,CURRENT_TIMESTAMP);
INSERT INTO "Theme" ("id","name","slug","background","typography","buttons","cards","updatedAt") VALUES ('7523be14-9888-597b-9558-9b4a97954307','Nature','nature','{"type": "solid", "color": "#F0FDF4"}'::jsonb,'{"fontFamily": "system", "titleSize": 32, "color": "#14532D"}'::jsonb,'{"variant": "filled", "radius": 16, "background": "#166534", "color": "#FFFFFF", "shadow": false}'::jsonb,'{"radius": 16, "background": "#F0FDF4", "blur": 0}'::jsonb,CURRENT_TIMESTAMP);
INSERT INTO "PageTemplate" ("key","name","description","themeKey","blocks") VALUES ('starter','Starter','A short introduction and website link.','minimal','[{"type": "TEXT", "content": {"text": "Welcome! Replace this introduction with your own.", "alignment": "left"}, "isVisible": true}, {"type": "LINK", "content": {"title": "Replace with your website", "url": "https://example.com/", "openInNewTab": true}, "isVisible": true}]');
INSERT INTO "PageTemplate" ("key","name","description","themeKey","blocks") VALUES ('creator','Creator','An introduction and two links for your work.','gradient','[{"type": "TEXT", "content": {"text": "Welcome! Replace this introduction with your own.", "alignment": "left"}, "isVisible": true}, {"type": "LINK", "content": {"title": "Replace with your website", "url": "https://example.com/", "openInNewTab": true}, "isVisible": true}, {"type": "LINK", "content": {"title": "Replace with your latest work", "url": "https://example.com/work", "openInNewTab": true}, "isVisible": true}]');
INSERT INTO "PageTemplate" ("key","name","description","themeKey","blocks") VALUES ('professional','Professional','An introduction and portfolio link.','professional','[{"type": "TEXT", "content": {"text": "Welcome! Replace this introduction with your own.", "alignment": "left"}, "isVisible": true}, {"type": "LINK", "content": {"title": "Replace with your website", "url": "https://example.com/", "openInNewTab": true}, "isVisible": true}]');
ALTER TABLE "Page" ADD COLUMN "appearanceOverrides" JSONB NOT NULL DEFAULT '{}';
ALTER TABLE "Page" ADD CONSTRAINT "Page_themeKey_fkey" FOREIGN KEY ("themeKey") REFERENCES "Theme"("slug") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE TYPE "SocialPlatform" AS ENUM ('INSTAGRAM','YOUTUBE','X','LINKEDIN','FACEBOOK','TIKTOK','GITHUB','DISCORD','TWITCH','SPOTIFY');
CREATE TABLE "SocialProfile" (
 "id" TEXT NOT NULL PRIMARY KEY, "pageId" TEXT NOT NULL, "platform" "SocialPlatform" NOT NULL,
 "username" TEXT, "url" TEXT NOT NULL, "position" INTEGER NOT NULL, "isVisible" BOOLEAN NOT NULL DEFAULT true,
 "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL,
 CONSTRAINT "SocialProfile_position_nonnegative" CHECK ("position" >= 0),
 CONSTRAINT "SocialProfile_pageId_fkey" FOREIGN KEY ("pageId") REFERENCES "Page"("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX "SocialProfile_pageId_position_idx" ON "SocialProfile"("pageId","position");

-- Additional system themes, normalized to the current ThemeConfig contract.
INSERT INTO "Theme" ("id","name","slug","background","typography","buttons","cards","updatedAt") VALUES ('44e87474-6a78-552f-9504-d1b03a47b8d6','Aurora','aurora','{"type": "gradient", "from": "#07060f", "to": "#171331", "angle": 160}'::jsonb,'{"fontFamily": "sans", "titleSize": 32, "color": "#FFFFFF"}'::jsonb,'{"variant": "filled", "radius": 24, "background": "#6c5cff", "color": "#FFFFFF", "shadow": true}'::jsonb,'{"radius": 24, "background": "#07060f", "blur": 0}'::jsonb,CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Theme" ("id","name","slug","background","typography","buttons","cards","updatedAt") VALUES ('31e71197-56ba-5fe6-9700-f382b0b3792d','Neon Pop','neon-pop','{"type": "gradient", "from": "#0a0a12", "to": "#04121a", "angle": 160}'::jsonb,'{"fontFamily": "sans", "titleSize": 32, "color": "#FFFFFF"}'::jsonb,'{"variant": "glass", "radius": 24, "background": "#ff3df0", "color": "#FFFFFF", "shadow": true}'::jsonb,'{"radius": 24, "background": "#0a0a12", "blur": 12}'::jsonb,CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Theme" ("id","name","slug","background","typography","buttons","cards","updatedAt") VALUES ('03219b78-0e71-53da-8332-3887d7020bbc','Cyan Pulse','cyan-pulse','{"type": "gradient", "from": "#03121a", "to": "#0a0f2a", "angle": 160}'::jsonb,'{"fontFamily": "sans", "titleSize": 32, "color": "#FFFFFF"}'::jsonb,'{"variant": "filled", "radius": 24, "background": "#22e3ff", "color": "#FFFFFF", "shadow": true}'::jsonb,'{"radius": 24, "background": "#03121a", "blur": 0}'::jsonb,CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Theme" ("id","name","slug","background","typography","buttons","cards","updatedAt") VALUES ('5a0d70e4-bfbe-59ae-ade0-0688787e59e1','Sunset Lime','sunset-lime','{"type": "gradient", "from": "#0f1206", "to": "#0a1a10", "angle": 160}'::jsonb,'{"fontFamily": "sans", "titleSize": 32, "color": "#FFFFFF"}'::jsonb,'{"variant": "outline", "radius": 24, "background": "#9dff3d", "color": "#FFFFFF", "shadow": true}'::jsonb,'{"radius": 24, "background": "#0f1206", "blur": 0}'::jsonb,CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Theme" ("id","name","slug","background","typography","buttons","cards","updatedAt") VALUES ('3cd9aa4d-caf7-50d8-9f5f-5548d47740cf','Coral Drift','coral-drift','{"type": "gradient", "from": "#120608", "to": "#10060f", "angle": 160}'::jsonb,'{"fontFamily": "sans", "titleSize": 32, "color": "#FFFFFF"}'::jsonb,'{"variant": "filled", "radius": 24, "background": "#ff5e7a", "color": "#FFFFFF", "shadow": true}'::jsonb,'{"radius": 24, "background": "#120608", "blur": 0}'::jsonb,CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
